AWSTemplateFormatVersion: 2010-09-09
Description: Setup AWS IoT Policies and IAM Roles
Resources:
  IoTProvisioningRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IoTProvisioning
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: iot.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: ThingRegistrationPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - iot:*
            Resource: '*'
      - PolicyName: ThingRegistrationLogginPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: '*'
      - PolicyName: ThingRegistrationRuleActionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            - kinesis:PutRecord
            - iot:Publish
            - s3:PutObject
            - sns:Publish
            - sqs:SendMessage*
            - cloudwatch:SetAlarmState
            - cloudwatch:PutMetricData
            - es:ESHttpPut
            - firehose:PutRecord
            Resource: '*'
  IoTAccessPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyName: IoTAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: MQTTConnect
          Action:
          - iot:Connect
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:iot:'
              - Fn::Sub: ${AWS::Region}
              - ':'
              - Fn::Sub: ${AWS::AccountId}
              - :client/${iot:Certificate.Subject.CommonName}
        - Sid: MQTTRead
          Action:
          - iot:Subscribe
          - iot:Receive
          Effect: Allow
          Resource: '*'
        - Sid: MQTTWrite
          Action:
          - iot:Publish
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:iot:'
              - Fn::Sub: ${AWS::Region}
              - ':'
              - Fn::Sub: ${AWS::AccountId}
              - :topic/${iot:Certificate.Subject.CommonName}
